name: onelenykco
description: onelenyk studio

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.8

  cupertino_icons: ^1.0.2
  dhttpd: ^4.0.1
  firebase_core: ^2.16.0
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  auto_route: ^7.8.4
  font_awesome_flutter: ^10.6.0
  flutter_emoji: ">= 2.0.0"
  carousel_slider: ^4.2.1
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  mailto: ^2.0.0
  url_launcher: ^6.2.1
  http: ^1.1.0
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.2
  json_serializable: ^6.7.1
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
  fonts:
    - family: Bandana
      fonts:
        - asset: assets/fonts/bandana.ttf


flutter_web_plugins:
  sdk: flutter