# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:web)

platform :web do
  desc "Deploy new version build"
  lane :deploy do
    # add actions here: https://docs.fastlane.tools/actions
      sh("./fruit_version_release.sh")
      sh("./fruit_version_build.sh")
      sh("flutter build web")
      sh("firebase deploy")
  end

  desc "Update current version build"
  lane :deployCurrent do
      # add actions here: https://docs.fastlane.tools/actions
      sh("./fruit_version_build.sh")
      sh("flutter build web")
      sh("firebase deploy")
  end


desc "Deploy current version build to Demo with a random channel"
lane :deployCurrentToDemo do
    # Your existing actions
    sh("./fruit_version_build.sh")
    sh("flutter build web")
    # Generate a random channel ID using shell commands
    channel_id = sh("echo $(date +%s)$(openssl rand -hex 5)").strip
    sh("firebase hosting:channel:deploy #{channel_id}")
end
  desc "Print current build version"
  lane :printCurrent do
        # add actions here: https://docs.fastlane.tools/actions
      sh("./fruit_print_version.sh")
  end
end
