# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:web)

platform :web do
  desc "Deploy new version"
  lane :deploy do
    # add actions here: https://docs.fastlane.tools/actions
      sh("fruit_version_build.sh")
      sh("fruit_version_release.sh")
      sh("flutter build web")
      sh("firebase deploy")
  end

  desc "Update current version"
  lane :deployCurrent do
      # add actions here: https://docs.fastlane.tools/actions
      sh("fruit_version_build.sh")
      sh("flutter build web")
      sh("firebase deploy")
  end

  desc "Print current build version"
  lane :printCurrent do
        # add actions here: https://docs.fastlane.tools/actions
      sh("./fruit_print_version.sh")
  end
end
